### ISSUE TITLE
Release process track

### ISSUE THREAD

**Issue by xueqianj** [splunk/CitrixCloudAddOnForSplunk#3]
Hi team, 

I see the new version (1.0.1) is still in release process and not available for Splunk Cloud now because it has not passed Appinspect and contains some external libraries that need further approval, so could you help to point me where I can track the release process?  Thanks!

**Comment by ScriptBlock** [comment]
There is not an external-facing portal that shows these details.  However, I can share that version 1.0.2 is actually now in the release pipeline as there were additional permissions fixes required to get validated for Splunk Cloud.  1.0.2 is pending review now.  I can't give an timeframe for release, but it is being worked on.

**Comment by ScriptBlock** [comment]
in working with citrix, we identified a number of issues interfacing with their API.  these fixed are being implemented now which including token fetching, pagination issues, and time intervals on configlogs.  these changes will be released asap.  You can see the work in progress and build this package on your own using the ucc framework if you take a look at branch 003
https://github.com/splunk/CitrixCloudAddOnForSplunk/tree/SPLK-003

**Comment by ScriptBlock** [comment]
This has been merged, and version 1.1.0 is being updated in Splunkbase today.  It includes citrix cloud api fixes, general python bugs, and some updated data scheduling capabilities.  The citrix logs api has some hard coded intervals for retrieving data.  the default is now 1 day, so cron scheduling of that input to execute near midnight is the likely pattern.

**Comment by ScriptBlock** [comment]
1.1.0 should address cloud vetting and bugfixes
