### ISSUE TITLE
Pagination returning 404

### ISSUE THREAD

**Issue by bobgit202** [splunk/CitrixCloudAddOnForSplunk#4]
There is an issue where it is only fetching 250 records from Citrix.

After much debugging, I found there when calling the next URL with the ContinuationToken, Citrix keeps returning 404 message.

Where there is
`getRecordsUrl = "{}&ContinuationToken={}".format(getRecordsUrl, continuationToken)`
it should read
`getRecordsUrl = "{}?ContinuationToken={}".format(getRecordsUrl, continuationToken)`

This small change resulted in fetching loads more events from Citrix.

**Comment by ScriptBlock** [comment]
Good catch.  Changes in SPLK-003, will merge with some other changes asap.

**Comment by ScriptBlock** [comment]
Should note.  I think this is only relevant to cvad_operational.py.  The configlogs and systemlogs have a searcDateOption url parameter, so the & notation should be correct there.
